### ISSUE TITLE
Possible docker image?

### ISSUE THREAD

**Issue by zhangysh1995** [tum-i4/munch#7]
Hi, I just want to know could it be possible if I use a `KLEE` docker image to install all the dependencies?

**Comment by saahil** [comment]
Hi, at the moment you can't do that, unfortunately. In fact, as you may have seen from the installation docs, you need our specialized fork of KLEE (not available as a Docker image) and not whatever the latest version of original KLEE is. 

There are currently no plans to have a Docker image for Munch, we are actively working on the cousin project Macke at the moment.
